name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - jupyterlab=3.0.12
  - seaborn=0.11.1
  - pandas
  - pip=20.3.3
  - pyarrow=2.0
  - ydata-profiling
  - ipywidgets
  - pip:
      - wandb==0.10.31